import { StyleSheet } from 'react-native';

export const hybridStyles = StyleSheet.create({
  // Main Container
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  backgroundGradient: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },

  // Header Styles
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 215, 0, 0.2)',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.3)',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFD700',
    textAlign: 'center',
  },
  headerUnderline: {
    width: 50,
    height: 2,
    borderColor: 'transparent',
    borderRadius: 1,
    marginTop: 2,
  },
  headerRight: {
    width: 40,
    alignItems: 'center',
  },

  // Scroll View
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 40,
  },

  // Introduction Section
  introduction: {
    paddingHorizontal: 20,
    paddingVertical: 30,
    alignItems: 'center',
  },
  introTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFD700',
    textAlign: 'center',
    marginBottom: 15,
  },
  introDescription: {
    fontSize: 16,
    color: '#CCCCCC',
    textAlign: 'center',
    lineHeight: 24,
    paddingHorizontal: 20,
  },

  // SLIDER
  sliderContainer: {
    paddingHorizontal: 20,
    paddingVertical: 30,
    backgroundColor: 'rgba(26, 26, 26, 0.8)',
    marginHorizontal: 20,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 15,
    marginBottom: 30,
  },
  sliderHeader: {
    alignItems: 'center',
    marginBottom: 20,
  },
  sliderTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFD700',
    marginBottom: 15,
    textAlign: 'center',
  },
  currentProfileIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  currentProfileText: {
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 8,
  },

  // Slider Labels
  sliderLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  labelContainer: {
    alignItems: 'center',
    flex: 1,
  },
  sliderLabel: {
    fontSize: 12,
    color: '#666666',
    marginTop: 5,
    fontWeight: '600',
  },
  activeLabel: {
    color: '#FFD700',
  },

  sliderWrapper: {
    position: 'relative',
    marginBottom: 25,
    paddingTop: 50,
  },

  floatingIcon: {
    position: 'absolute',
    top: -40,
    left: -20,
    zIndex: 10,
    alignItems: 'center',
  },
  iconBubble: {
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 2,
    borderColor: '#FFD700',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 50,
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 8,
    elevation: 8,
  },
  iconValue: {
    color: '#FFD700',
    fontSize: 12,
    fontWeight: 'bold',
    marginTop: 2,
  },
  iconArrow: {
    width: 0,
    height: 0,
    borderLeftWidth: 6,
    borderRightWidth: 6,
    borderTopWidth: 8,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#FFD700',
    marginTop: -1,
  },

  sliderTrack: {
    height: 8,
    backgroundColor: 'rgba(51, 51, 51, 0.8)',
    borderRadius: 4,
    overflow: 'hidden',
    position: 'relative',
  },
  sliderTrackFill: {
    height: '100%',
    borderRadius: 4,
    overflow: 'hidden',
  },
  sliderKnob: {
    position: 'absolute',
    top: -16,
    width: 40,
    height: 40,
    borderRadius: 20,
    borderColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 10,
    borderWidth: 3,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  knobCenter: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FFF',
  },

  // Scale Numbers
  scaleNumbers: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 5,
    marginTop: 15,
  },
  scaleNumberContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 30,
    height: 30,
  },
  scaleNumber: {
    fontSize: 12,
    color: '#666666',
    fontWeight: '600',
  },
  activeScaleNumber: {
    color: '#FFD700',
    fontSize: 14,
    fontWeight: 'bold',
  },

  // Profile Display
  profileDisplay: {
    backgroundColor: 'rgba(26, 26, 26, 0.95)',
    marginHorizontal: 20,
    borderRadius: 20,
    padding: 25,
    borderWidth: 2,
    borderColor: '#FFD700',
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 15 },
    shadowOpacity: 0.6,
    shadowRadius: 25,
    elevation: 20,
    marginBottom: 30,
    position: 'relative',
    overflow: 'hidden',
  },
  glassOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '50%',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  profileDisplayGlow: {
    position: 'absolute',
    top: -10,
    left: -10,
    right: -10,
    bottom: -10,
    borderRadius: 30,
    opacity: 0.1,
  },
  profileImageWrapper: {
    alignItems: 'center',
    marginBottom: 25,
  },
  rouletteWheel: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 4,
    borderColor: '#FFD700',
    backgroundColor: 'rgba(26, 26, 26, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  rouletteCenter: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  rouletteNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFD700',
  },
  profileInfoDisplay: {
    alignItems: 'center',
  },
  profileTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFD700',
    marginBottom: 10,
    textAlign: 'center',
  },
  profileDescription: {
    fontSize: 16,
    color: '#CCCCCC',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  profileStats: {
    width: '100%',
    marginBottom: 20,
  },
  statItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderRadius: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  statLabel: {
    fontSize: 14,
    color: '#CCCCCC',
    fontWeight: '500',
  },
  statValue: {
    fontSize: 14,
    fontWeight: 'bold',
  },

  featuresContainer: {
    width: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderRadius: 15,
    padding: 15,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  featuresTitle: {
    fontSize: 16,
    color: '#FFD700',
    fontWeight: 'bold',
    marginBottom: 12,
    textAlign: 'center',
  },
  featureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    paddingLeft: 5,
  },
  featureText: {
    fontSize: 14,
    color: '#CCCCCC',
    marginLeft: 10,
    flex: 1,
  },
  depthIndicator: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },

  actionButtons: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  saveButton: {
    borderColor: 'transparent',
    borderRadius: 15,
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
    elevation: 15,
    overflow: 'hidden',
  },
  buttonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    paddingHorizontal: 30,
    borderRadius: 15,
  },
  buttonIcon: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 20,
    padding: 6,
    marginRight: 10,
  },
  saveButtonText: {
    color: '#000000',
    fontSize: 18,
    fontWeight: 'bold',
  },

  riskWarning: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 12,
    padding: 15,
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 40,
  },
  riskWarningText: {
    fontSize: 14,
    marginLeft: 10,
    flex: 1,
    lineHeight: 20,
  },
});

export const modalStyles = StyleSheet.create({
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.8)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContainer: {
      width: '90%',
      maxWidth: 400,
      backgroundColor: '#1E1E1E',
      borderRadius: 15,
      borderWidth: 1,
      borderColor: 'rgba(255, 215, 0, 0.3)',
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(255, 215, 0, 0.2)',
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#FFD700',
    },
    modalCloseButton: {
      padding: 5,
    },
    modalContent: {
      padding: 20,
      maxHeight: 300,
    },
    inputContainer: {
      marginBottom: 20,
    },
    inputLabel: {
      fontSize: 14,
      color: '#CCCCCC',
      marginBottom: 8,
    },
    inputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.3)',
      borderRadius: 10,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    currencySymbol: {
      color: '#FFD700',
      fontSize: 18,
      paddingLeft: 15,
    },
    modalInput: {
      flex: 1,
      color: '#FFFFFF',
      fontSize: 18,
      padding: 15,
    },
    errorText: {
      color: '#F44336',
      marginTop: 8,
      fontSize: 12,
    },
    presetContainer: {
      marginTop: 10,
    },
    presetTitle: {
      color: '#CCCCCC',
      marginBottom: 10,
      fontSize: 14,
    },
    presetButtons: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    presetButton: {
      backgroundColor: 'rgba(255, 215, 0, 0.1)',
      borderRadius: 8,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: 'rgba(255, 215, 0, 0.3)',
      alignItems: 'center',
    },
    presetButtonText: {
      color: '#FFD700',
      fontWeight: 'bold',
    },
    presetValueText: {
      color: '#FFFFFF',
      fontSize: 12,
      marginTop: 2,
    },
    modalActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      padding: 20,
      borderTopWidth: 1,
      borderTopColor: 'rgba(255, 215, 0, 0.2)',
    },
    cancelButton: {
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 8,
    },
    cancelButtonText: {
      color: '#CCCCCC',
    },
    saveButton: {
      backgroundColor: '#FFD700',
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 8,
      marginLeft: 10,
    },
    saveButtonText: {
      color: '#000000',
      fontWeight: 'bold',
    },
  });